name: Crossbow
on: 
  push:
    branches: r-nightly-testing
    
jobs:
  test:
    runs-on: [self-hosted, Windows]
    steps:
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "release"
