name: Crossbow
on: 
  push:
    branches: r-nightly-testing
    
jobs:
  test:
    runs-on: [self-hosted, Windows]
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            console.log(process.platform)
